name: Generate Snake Animation

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar o script manualmente na aba "Actions"
  workflow_dispatch:
  
  # Roda toda vez que você fizer um push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Gera a animação da cobrinha a partir das suas contribuições
      - name: Generate github-contribution-grid-snake.svg
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: magnomct
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Faz o push dos arquivos gerados para a branch "output"
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
